### PR TITLE
fix: altsource spec

### PR DESCRIPTION
**Pull request by castdrian**
it would seem you accidentally broke the altsource by adding that key to the apps object lol

### CODE REVIEW

**Comment by castdrian** [comment]
correction, looking at it, the workflow caused it, so it would seem I accidentally broke it kek

**Comment by amsryq** [comment]
nope that was me, it was introduced in https://github.com/pyoncord/BunnyTweak/commit/5a2e8c13e52a3b9619b2c9e5be2d8c9edb406db2 supposedly fixes sidestore (a user confimed that it does fix it)
i assumed it'd work because [a trusted AltStore source](https://altstore.oatmealdome.me/) does that and it's just an extra entry, i expected altstore to ignore it
you're right about it not being in the spec tho, does it really break with vanilla AltStore?

**Comment by castdrian** [comment]
looking at the support channel it would seem so, I have PAL so normal sources don't work for me anyway, however I've been talking to shane from altstore anyway since I distribute on PAL so I can ask them if they plan on perhaps having it ignore random keys

**Comment by castdrian** [comment]
supersedet by https://github.com/pyoncord/BunnyTweak/pull/9

**Pull request closed without merging**
